$(shell mkdir -p /mnt/disk/jenkins/ci/workspace/chipset_patch2/opensource/component_code/out/target/product/kirin970/obj/KERNEL_OBJ/arch/arm64/boot/dts/auto-generate/overlay/kirin970)
include /mnt/disk/jenkins/ci/workspace/chipset_patch2/opensource/component_code/kernel/linux-4.14/arch/arm64/boot/dts/auto-generate/overlay/kirin970/kirin970_dtb.mk
dtbs: kirin970_dtbo
